gamehub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('gamehubs.urls'))

]

gamehubs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path
from . import views
app_name = "gamehubs"
urlpatterns = [
    #Home page
    path('', views.index, name='index'),
    path('homepage/', views.homepage, name='games'),
    path('homepage/<int:game_id>/', views.game, name='game'),
    #adding new books
    path('profile/', views.profile, name='profile'),
    path('game/<int:game_id>/scores/', views.game_scores, name='game_scores'),
    path('new_review/<int:game_id>/', views.new_review, name='new_review'),
    #path('edit_review/<int:review_id>/', views.edit_review, name='edit_review')
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views
app_name = "users"
urlpatterns = [
    #include default auth urls
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

gamehubs/models.py
from django.db import models
from django.contrib.auth.models import User


class Game(models.Model):
    name = models.CharField(max_length=100)
    creator = models.CharField(max_length=100)
    rating = models.FloatField(default=0.0)

    def __str__(self):
        return self.name


class GameReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    review = models.TextField(default="good")

    def __str__(self):
        return f"{self.game} - {self.rating}"


class Score(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)
    highest_score = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.game} - {self.user} - {self.points}"



users/models.py
from django.db import models

# Create your models here.

gamehubs/forms.py
from django import forms

from .models import Game, GameReview, Score


class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'creator', 'rating']
        labels = {'name': ''}


class ReviewForm(forms.ModelForm):
    class Meta:
        model = GameReview
        fields = ['review', 'rating']
        labels = {'review': ''}
        

class Score(forms.ModelForm):
    class Meta:
        model = Score
        fields = ['points']
        labels = {'points' : ''}

gamehubs/views.py
import random

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Game, GameReview, Score
from django.db.models import Avg
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import ReviewForm
from random import randint
from django.db.models import Max



def index(request):
    return render(request, 'gamehubs/index.html')

def homepage(request):
    games = Game.objects.all()
    context = {'games':games}
    return render(request, 'gamehubs/homepage.html', context)


def game(request, game_id):
    game = get_object_or_404(Game, id=game_id)
    calculate_game_rating(game_id)

    # Get the top score for each user on this game
    high_scores = Score.objects.filter(game=game).values('user__username').annotate(max_score=Max('points'))

    # Get the scores for the current user on this game
    try:
        user_score = Score.objects.get(user=request.user, game=game)
    except Score.DoesNotExist:
        user_score = None

    if request.method == 'POST':
        # Handle form submission
        score_value = random.randint(1, 1000)
        score, created = Score.objects.get_or_create(user=request.user, game=game)
        if score_value > score.points:
            score.points = score_value
            score.save()

        return HttpResponseRedirect(reverse('gamehubs:game', args=[game_id]))
    else:
        # Render game page with "play" button
        reviews = GameReview.objects.filter(game=game)
        high_scores = [{'username': score['user__username'], 'max_score': score['max_score']} for score in high_scores]
        context = {'game': game, 'reviews': reviews, 'form': ReviewForm(),
                   'high_scores': high_scores, 'user_score': user_score}
        return render(request, 'gamehubs/game.html', context)


@login_required
def profile(request):
    user_scores = Score.objects.filter(user=request.user).select_related('game').order_by('-points')
    games_played = set(score.game for score in user_scores)

    past_games = list(games_played)
    high_scores = []
    for game in games_played:
        high_score = Score.objects.filter(game=game, user=request.user).order_by('-points').first()
        if high_score:
            high_scores.append(high_score)

    context = {
        'past_games': past_games,
        'high_scores': high_scores,
    }
    return render(request, 'gamehubs/profile.html', context)




@login_required
def game_scores(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    user_scores = Score.objects.filter(game=game, user=request.user).order_by('-points')
    reviews = GameReview.objects.filter(game=game, user=request.user)

    context = {
        'game': game,
        'scores': user_scores,
        'reviews': reviews,
    }
    return render(request, 'gamehubs/game_scores.html', context)



@login_required
def new_review(request, game_id):
    game = get_object_or_404(Game, id=game_id)

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.game = game
            review.user = request.user
            review.save()
            return HttpResponseRedirect(reverse('gamehubs:game', args=[game_id]))
    else:
        form = ReviewForm()

    context = {'game': game, 'form': form}
    calculate_game_rating(game_id)
    return render(request, 'gamehubs/new_review.html', context)


@login_required
def edit_review(request, review_id):
    review = get_object_or_404(GameReview, id=review_id)

    if request.user != review.user:
        # User does not have permission to edit this review
        return HttpResponseRedirect(reverse('gamehubs:game', args=[review.game.id]))

    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('gamehubs:game', args=[review.game.id]))
    else:
        form = ReviewForm(instance=review)

    context = {'game': review.game, 'form': form, 'review': review}
    return render(request, 'gamehubs/edit_review.html', context)


def calculate_game_rating(game_id):
    ratings = GameReview.objects.filter(game=game_id)
    if ratings:
        avg_rating = sum([rating.rating for rating in ratings])/len(ratings)
        game = Game.objects.get(id=game_id)
        game.rating = round(avg_rating, 1)
        game.save()
    else:
        game = Game.objects.get(id=game_id)
        game.rating = 0
        game.save()


users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('gamehubs:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

gamehubs/templates/gamehubs/base.html
<!DOCTYPE html>
{% load bootstrap4  %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Game Hub</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <a class="navbar-brand" href="{% url 'gamehubs:index' %}">Game Hub</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggle-icon"></span>
      </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
              <a href="{% url 'gamehubs:games' %}">Games</a>
              <a href="{% url 'gamehubs:profile' %}">Profile</a>
          </li>
      </ul>
      <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
              <li class="nav-item">
                  <span class="navbar-text">Hello,{{ user.username }}</span>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
              </li>
          {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:register' %}">Register</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
              </li>
          {% endif %}
      </ul>
  </div>
  </nav>
  <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
          {% block page-header %}{% endblock page-header %}
      </div>
      <div>
          {% block content %}{% endblock content %}
      </div>

  </main>
</body>
</html>

gamehubs/templates/gamehubs/edit_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'crazy_book_clubs/base.html' %}

{% block content %}

    <p><a href="{% url 'gamehubs:game' game.id %}">{{ game }}</a></p>
    <p>Edit entry:</p>
    <form action="{% url 'gamehubs:edit_review' review.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>

{% endblock content %}
</body>
</html>

gamehubs/templates/gamehubs/game.html
{% extends 'gamehubs/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1>{{ game.name }}</h1>
                <p>Rating: {{ game.rating }}</p>

                <form method="post" action="{% url 'gamehubs:game' game.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Play game</button>
                </form>
            </div>
            <div class="col-md-4">
                <h2>High Scores:</h2>
                <ul class="list-group">
                    {% for score in high_scores %}
                        <li class="list-group-item">{{ score.username }}: {{ score.max_score }}</li>
                    {% empty %}
                        <li class="list-group-item">No high scores yet.</li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-md-12">
                <h2>Reviews:</h2>

                <a href="{% url 'gamehubs:new_review' game.id %}" class="btn btn-primary mb-3">New Review</a>

                {% for review in reviews %}
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ review.rating }} - {{ review.user.username }}</h5>
                        <p class="card-text">{{ review.review }}</p>
                    </div>
                </div>
                {% empty %}
                    <p>No reviews yet.</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

gamehubs/templates/gamehubs/game_scores.html
{% extends 'gamehubs/base.html' %}

{% block content %}
    <div class="container mt-4">
        <h1>{{ game.name }} Scores and Reviews</h1>

        <div class="row mt-4">
            <div class="col-md-6">
                <h2>Scores:</h2>
                {% if scores %}
                    <ul class="list-group">
                        {% for score in scores %}
                            <li class="list-group-item">{{ score.points }}</li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>No scores yet.</p>
                {% endif %}
            </div>

            <div class="col-md-6">
                <h2>Reviews:</h2>
                <a href="{% url 'gamehubs:new_review' game.id %}" class="btn btn-primary mb-4">New Review</a>

                {% for review in reviews %}
                    {% if request.user == review.user %}
                        <div class="card mb-3">
                            <div class="card-body">
                                <h5 class="card-title">
                                    {{ review.rating }}/5 - {{ review.title }}
                                </h5>
                                <p class="card-text">{{ review.review }}</p>
                            </div>
                        </div>
                    {% else %}
                        <div class="card mb-3">
                            <div class="card-body">
                                <h5 class="card-title">
                                    {{ review.rating }}/5 - {{ review.title }}
                                </h5>
                                <p class="card-text">{{ review.review }}</p>
                                <p class="card-text"><small class="text-muted">~{{ review.user.username }}</small></p>
                            </div>
                        </div>
                    {% endif %}
                {% empty %}
                    <p>No reviews yet.</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

gamehubs/templates/gamehubs/homepage.html
{% extends 'gamehubs/base.html' %}

{% block page_header %}
    <h1 class="display-4">Games</h1>
{% endblock page_header %}

{% block content %}

    <p class="lead">Games:</p>

    <ul class="list-group">
        {% for game in games %}
            <li class="list-group-item">
                <h3 class="mb-0">
                    <a href="{% url 'gamehubs:game' game.id %}" class="text-decoration-none">{{ game }}</a>
                </h3>
            </li>
        {% empty %}
            <li class="list-group-item"><h3 class="mb-0">No games have been added yet.</h3></li>
        {% endfor %}
    </ul>

{% endblock content %}

gamehubs/templates/gamehubs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "gamehubs/base.html" %}

{% block page-header %}
    <div class="jumbotron">
        <h1 class="display-3">Play what you love. Become the best.</h1>

        <p class="lead">Register a new account now to start playing, or log in to view your profile!</p>
        {% if user.is_authenticated %}
        <a class="btn btn-lg btn-primary" href="{% url 'gamehubs:games' %}" role="button">Games &raquo;</a>
        <a class="btn btn-lg btn-primary" href="{% url 'gamehubs:profile' %}" role="button">Profile &raquo;</a>
        {% else %}
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
        <a class="btn btn-lg btn-secondary" href="{% url 'users:login' %}" role="button">Log in &raquo;</a>
    {% endif %}
    </div>
{% endblock page-header %}

</body>
</html>

gamehubs/templates/gamehubs/new_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'gamehubs/base.html' %}
{% block content %}
    <p><a href="{% url 'gamehubs:game' game.id %}">{{ game }}</a></p>
    <p>Add a new review: </p>
    <form action="{% url 'gamehubs:new_review' game.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add review</button>
    </form>
{% endblock content %}
</body>
</html>

gamehubs/templates/gamehubs/profile.html
{% extends 'gamehubs/base.html' %}

{% block content %}
    <div class="container">
        <h1 class="mt-5">{{ request.user.username }}'s Profile</h1>

        <h2 class="mt-5">High Scores:</h2>
        {% if high_scores %}
            <ul class="list-group mb-5">
                {% for score in high_scores %}
                    {% if score.game %}
                        <li class="list-group-item">{{ score.game.name }} - {{ score.points }}</li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% else %}
            <p>No high scores yet.</p>
        {% endif %}

        <h2 class="mt-5">Past Games:</h2>
        {% if past_games %}
            <ul class="list-group mb-5">
                {% for game in past_games %}
                    <li class="list-group-item"><a href="{% url 'gamehubs:game_scores' game.id %}">{{ game.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No past games yet.</p>
        {% endif %}
    </div>
{% endblock %}